env: production
description: "Reaches deeper than the darkness."
author: inishaikhalishan
keywords: [Security, Linux, Programmer]

homeInfoParams:
 Title: inishaikhalishan
 Content: Hello, welcome to [inishaikhalishan](/)'s blog.
defaultTheme: dark
ShowReadingTime: false
ShowCodeCopyButtons: true
showtoc: true
ShowPostNavLinks: true
ShowShareButtons: true
disableScrollToTop: true
ShowWordCount: false
ShowFullTextinRSS: true

sitemap:
 changeFreq: "hourly"
 disable: false
 filename: sitemap.xml
 priority: -1

social: true
socialIcons:
  - name: "github"
    url: "https://github.com/"
  - name: "telegram"
    url: "https://t.me"
  - name: "rss"
    url: "/rss.xml"

label:
  text: " "
  icon: /logo/iniridwanul.png
  iconHeight: 40

assets:
  disableFingerprinting: true
  favicon: "/favicon/favicon.ico"
  favicon16x16: "/favicon/favicon-16x16.png"
  favicon32x32: "/favicon/favicon-32x32.png"
  apple_touch_icon: "/favicon/apple-touch-icon.png"

cover:
  hidden: true
  hiddenInSingle: true
  relative: false
  responsiveImages: true