baseURL = 'https://inishaikhalishan.github.io'
languageCode = 'en-us'
title = 'inishaikhalishan'
theme = 'hugo-PaperMod'
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"

[pagination]
pagerSize = "6"